language: perl
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1   # enables coverage+coveralls reporting
    - perl: 5.12
      env: COVERAGE=0 
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
deploy:
  provider: script
  script: $TRAVIS_BUILD_DIR/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    #tags: true
    perl: 5.24
